/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaoGiaRouteImport } from './routes/bao-gia'
import { Route as TimKiemRouteImport } from './routes/tim-kiem'
import { Route as DuAnIndexRouteImport } from './routes/du-an.index'
import { Route as TinSlugRouteImport } from './routes/tin.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaoGiaRoute = BaoGiaRouteImport.update({
  id: '/bao-gia',
  path: '/bao-gia',
  getParentRoute: () => rootRouteImport,
} as any)
const TimKiemRoute = TimKiemRouteImport.update({
  id: '/tim-kiem',
  path: '/tim-kiem',
  getParentRoute: () => rootRouteImport,
} as any)
const DuAnIndexRoute = DuAnIndexRouteImport.update({
  id: '/du-an/',
  path: '/du-an/',
  getParentRoute: () => rootRouteImport,
} as any)
const TinSlugRoute = TinSlugRouteImport.update({
  id: '/tin/$slug',
  path: '/tin/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bao-gia': typeof BaoGiaRoute
  '/tim-kiem': typeof TimKiemRoute
  '/tin/$slug': typeof TinSlugRoute
  '/du-an/': typeof DuAnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bao-gia': typeof BaoGiaRoute
  '/tim-kiem': typeof TimKiemRoute
  '/tin/$slug': typeof TinSlugRoute
  '/du-an': typeof DuAnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bao-gia': typeof BaoGiaRoute
  '/tim-kiem': typeof TimKiemRoute
  '/tin/$slug': typeof TinSlugRoute
  '/du-an/': typeof DuAnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bao-gia' | '/tim-kiem' | '/tin/$slug' | '/du-an/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bao-gia' | '/tim-kiem' | '/tin/$slug' | '/du-an'
  id: '__root__' | '/' | '/bao-gia' | '/tim-kiem' | '/tin/$slug' | '/du-an/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaoGiaRoute: typeof BaoGiaRoute
  TimKiemRoute: typeof TimKiemRoute
  TinSlugRoute: typeof TinSlugRoute
  DuAnIndexRoute: typeof DuAnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bao-gia': {
      id: '/bao-gia'
      path: '/bao-gia'
      fullPath: '/bao-gia'
      preLoaderRoute: typeof BaoGiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-kiem': {
      id: '/tim-kiem'
      path: '/tim-kiem'
      fullPath: '/tim-kiem'
      preLoaderRoute: typeof TimKiemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/du-an/': {
      id: '/du-an/'
      path: '/du-an'
      fullPath: '/du-an/'
      preLoaderRoute: typeof DuAnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin/$slug': {
      id: '/tin/$slug'
      path: '/tin/$slug'
      fullPath: '/tin/$slug'
      preLoaderRoute: typeof TinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaoGiaRoute: BaoGiaRoute,
  TimKiemRoute: TimKiemRoute,
  TinSlugRoute: TinSlugRoute,
  DuAnIndexRoute: DuAnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
