/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaoGiaRouteImport } from './routes/bao-gia'
import { Route as DangKyRouteImport } from './routes/dang-ky'
import { Route as DangNhapRouteImport } from './routes/dang-nhap'
import { Route as DangTinRouteImport } from './routes/dang-tin'
import { Route as TaiKhoanRouteImport } from './routes/tai-khoan'
import { Route as TimKiemRouteImport } from './routes/tim-kiem'
import { Route as TinTucRouteImport } from './routes/tin-tuc'
import { Route as BaiVietSlugRouteImport } from './routes/bai-viet.$slug'
import { Route as DuAnIndexRouteImport } from './routes/du-an.index'
import { Route as DuAnSlugRouteImport } from './routes/du-an.$slug'
import { Route as ThanhVienIdRouteImport } from './routes/thanh-vien.$id'
import { Route as TinSlugRouteImport } from './routes/tin.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaoGiaRoute = BaoGiaRouteImport.update({
  id: '/bao-gia',
  path: '/bao-gia',
  getParentRoute: () => rootRouteImport,
} as any)
const DangKyRoute = DangKyRouteImport.update({
  id: '/dang-ky',
  path: '/dang-ky',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapRoute = DangNhapRouteImport.update({
  id: '/dang-nhap',
  path: '/dang-nhap',
  getParentRoute: () => rootRouteImport,
} as any)
const DangTinRoute = DangTinRouteImport.update({
  id: '/dang-tin',
  path: '/dang-tin',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiKhoanRoute = TaiKhoanRouteImport.update({
  id: '/tai-khoan',
  path: '/tai-khoan',
  getParentRoute: () => rootRouteImport,
} as any)
const TimKiemRoute = TimKiemRouteImport.update({
  id: '/tim-kiem',
  path: '/tim-kiem',
  getParentRoute: () => rootRouteImport,
} as any)
const TinTucRoute = TinTucRouteImport.update({
  id: '/tin-tuc',
  path: '/tin-tuc',
  getParentRoute: () => rootRouteImport,
} as any)
const BaiVietSlugRoute = BaiVietSlugRouteImport.update({
  id: '/bai-viet/$slug',
  path: '/bai-viet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DuAnIndexRoute = DuAnIndexRouteImport.update({
  id: '/du-an/',
  path: '/du-an/',
  getParentRoute: () => rootRouteImport,
} as any)
const DuAnSlugRoute = DuAnSlugRouteImport.update({
  id: '/du-an/$slug',
  path: '/du-an/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanhVienIdRoute = ThanhVienIdRouteImport.update({
  id: '/thanh-vien/$id',
  path: '/thanh-vien/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TinSlugRoute = TinSlugRouteImport.update({
  id: '/tin/$slug',
  path: '/tin/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bao-gia': typeof BaoGiaRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/dang-tin': typeof DangTinRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/tim-kiem': typeof TimKiemRoute
  '/tin-tuc': typeof TinTucRoute
  '/bai-viet/$slug': typeof BaiVietSlugRoute
  '/du-an/$slug': typeof DuAnSlugRoute
  '/thanh-vien/$id': typeof ThanhVienIdRoute
  '/tin/$slug': typeof TinSlugRoute
  '/du-an/': typeof DuAnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bao-gia': typeof BaoGiaRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/dang-tin': typeof DangTinRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/tim-kiem': typeof TimKiemRoute
  '/tin-tuc': typeof TinTucRoute
  '/bai-viet/$slug': typeof BaiVietSlugRoute
  '/du-an/$slug': typeof DuAnSlugRoute
  '/thanh-vien/$id': typeof ThanhVienIdRoute
  '/tin/$slug': typeof TinSlugRoute
  '/du-an': typeof DuAnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bao-gia': typeof BaoGiaRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/dang-tin': typeof DangTinRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/tim-kiem': typeof TimKiemRoute
  '/tin-tuc': typeof TinTucRoute
  '/bai-viet/$slug': typeof BaiVietSlugRoute
  '/du-an/$slug': typeof DuAnSlugRoute
  '/thanh-vien/$id': typeof ThanhVienIdRoute
  '/tin/$slug': typeof TinSlugRoute
  '/du-an/': typeof DuAnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bao-gia'
    | '/dang-ky'
    | '/dang-nhap'
    | '/dang-tin'
    | '/tai-khoan'
    | '/tim-kiem'
    | '/tin-tuc'
    | '/bai-viet/$slug'
    | '/du-an/$slug'
    | '/thanh-vien/$id'
    | '/tin/$slug'
    | '/du-an/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bao-gia'
    | '/dang-ky'
    | '/dang-nhap'
    | '/dang-tin'
    | '/tai-khoan'
    | '/tim-kiem'
    | '/tin-tuc'
    | '/bai-viet/$slug'
    | '/du-an/$slug'
    | '/thanh-vien/$id'
    | '/tin/$slug'
    | '/du-an'
  id:
    | '__root__'
    | '/'
    | '/bao-gia'
    | '/dang-ky'
    | '/dang-nhap'
    | '/dang-tin'
    | '/tai-khoan'
    | '/tim-kiem'
    | '/tin-tuc'
    | '/bai-viet/$slug'
    | '/du-an/$slug'
    | '/thanh-vien/$id'
    | '/tin/$slug'
    | '/du-an/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaoGiaRoute: typeof BaoGiaRoute
  DangKyRoute: typeof DangKyRoute
  DangNhapRoute: typeof DangNhapRoute
  DangTinRoute: typeof DangTinRoute
  TaiKhoanRoute: typeof TaiKhoanRoute
  TimKiemRoute: typeof TimKiemRoute
  TinTucRoute: typeof TinTucRoute
  BaiVietSlugRoute: typeof BaiVietSlugRoute
  DuAnSlugRoute: typeof DuAnSlugRoute
  ThanhVienIdRoute: typeof ThanhVienIdRoute
  TinSlugRoute: typeof TinSlugRoute
  DuAnIndexRoute: typeof DuAnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bao-gia': {
      id: '/bao-gia'
      path: '/bao-gia'
      fullPath: '/bao-gia'
      preLoaderRoute: typeof BaoGiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-ky': {
      id: '/dang-ky'
      path: '/dang-ky'
      fullPath: '/dang-ky'
      preLoaderRoute: typeof DangKyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-nhap': {
      id: '/dang-nhap'
      path: '/dang-nhap'
      fullPath: '/dang-nhap'
      preLoaderRoute: typeof DangNhapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-tin': {
      id: '/dang-tin'
      path: '/dang-tin'
      fullPath: '/dang-tin'
      preLoaderRoute: typeof DangTinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-khoan': {
      id: '/tai-khoan'
      path: '/tai-khoan'
      fullPath: '/tai-khoan'
      preLoaderRoute: typeof TaiKhoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-kiem': {
      id: '/tim-kiem'
      path: '/tim-kiem'
      fullPath: '/tim-kiem'
      preLoaderRoute: typeof TimKiemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin-tuc': {
      id: '/tin-tuc'
      path: '/tin-tuc'
      fullPath: '/tin-tuc'
      preLoaderRoute: typeof TinTucRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bai-viet/$slug': {
      id: '/bai-viet/$slug'
      path: '/bai-viet/$slug'
      fullPath: '/bai-viet/$slug'
      preLoaderRoute: typeof BaiVietSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/du-an/': {
      id: '/du-an/'
      path: '/du-an'
      fullPath: '/du-an/'
      preLoaderRoute: typeof DuAnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/du-an/$slug': {
      id: '/du-an/$slug'
      path: '/du-an/$slug'
      fullPath: '/du-an/$slug'
      preLoaderRoute: typeof DuAnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanh-vien/$id': {
      id: '/thanh-vien/$id'
      path: '/thanh-vien/$id'
      fullPath: '/thanh-vien/$id'
      preLoaderRoute: typeof ThanhVienIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin/$slug': {
      id: '/tin/$slug'
      path: '/tin/$slug'
      fullPath: '/tin/$slug'
      preLoaderRoute: typeof TinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaoGiaRoute: BaoGiaRoute,
  DangKyRoute: DangKyRoute,
  DangNhapRoute: DangNhapRoute,
  DangTinRoute: DangTinRoute,
  TaiKhoanRoute: TaiKhoanRoute,
  TimKiemRoute: TimKiemRoute,
  TinTucRoute: TinTucRoute,
  BaiVietSlugRoute: BaiVietSlugRoute,
  DuAnSlugRoute: DuAnSlugRoute,
  ThanhVienIdRoute: ThanhVienIdRoute,
  TinSlugRoute: TinSlugRoute,
  DuAnIndexRoute: DuAnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
